'use strict';
const icons=['house','soccer-ball','gear','caret-right','arrow-right','arrow-left','x','check','check-circle','warning-circle','info','magnifying-glass','speaker-high','speaker-slash','clock','trophy','users','wifi-slash','circle-notch'];
const colors=[['canvas','#013026'],['surface','#043A2F'],['raised','#124B38'],['primary','#DAEC5A'],['text','#FFFBEA'],['textMuted','#B6C6B9'],['borderControl','#78A38A']];
const swatches=document.getElementById('swatches');colors.forEach(([name,color])=>{const el=document.createElement('div');el.className='swatch';const sample=document.createElement('div');sample.style.background=color;const p=document.createElement('p');p.textContent=name;const b=document.createElement('b');b.textContent=color;p.append(b);el.append(sample,p);swatches.append(el);});
icons.forEach(name=>{const el=document.createElement('div');el.className='icon-cell';const img=document.createElement('img');img.className='icon';img.src='../assets/icons/'+name+'.svg';img.alt='';const span=document.createElement('span');span.textContent=name;el.append(img,span);document.getElementById('icon-grid').append(el);});
let toastTimeout;function toast(message){const el=document.getElementById('toast');el.querySelector('span').textContent=message;el.hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>{el.hidden=true;},4500);}
document.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',()=>toast(el.dataset.toast)));
document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===el)));document.getElementById('nav-state').textContent='Aktif: '+el.dataset.tab+' · bu örnek yalnız menü state’ini gösterir.';}));
document.querySelectorAll('.segmented button').forEach(el=>el.addEventListener('click',()=>{el.parentElement.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===el)));}));
const sound=document.getElementById('sound-switch');sound.addEventListener('click',()=>{const checked=sound.getAttribute('aria-checked')!=='true';sound.setAttribute('aria-checked',String(checked));document.getElementById('sound-state').textContent='Ses efektleri '+(checked?'açık.':'kapalı.');});
let selectedTeam=null,pendingTeam=null;const sheet=document.getElementById('team-sheet'),confirm=document.getElementById('confirm-team');function syncChoices(){document.querySelectorAll('[data-team]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.team===pendingTeam)));confirm.disabled=!pendingTeam;}function openTeam(){pendingTeam=selectedTeam;syncChoices();sheet.showModal();}
document.getElementById('choose-team').addEventListener('click',openTeam);document.querySelectorAll('[data-open-team]').forEach(b=>b.addEventListener('click',openTeam));document.querySelector('[data-close-team]').addEventListener('click',()=>sheet.close());document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>{pendingTeam=b.dataset.team;syncChoices();}));confirm.addEventListener('click',()=>{selectedTeam=pendingTeam;document.getElementById('selection-label').textContent=selectedTeam+' seçildi · Değiştir';sheet.close();toast('Seçimin kaydedildi: '+selectedTeam);});
sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)sheet.close();}});
document.querySelector('[data-scroll-matches]').addEventListener('click',()=>{document.getElementById('match-demo').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});toast('Haftanın maçları kart örneği');});
const exit=document.getElementById('exit-dialog');document.querySelectorAll('[data-open-exit]').forEach(b=>b.addEventListener('click',()=>exit.showModal()));document.getElementById('cancel-exit').addEventListener('click',()=>exit.close());document.getElementById('confirm-exit').addEventListener('click',()=>{exit.close();toast('Çıkış eylemi örneği tamamlandı.');});
const answer=document.getElementById('player-answer');document.getElementById('answer-form').addEventListener('submit',e=>{e.preventDefault();const invalid=!answer.value.trim();document.getElementById('answer-error').hidden=!invalid;answer.setAttribute('aria-invalid',String(invalid));if(invalid)answer.focus();else toast('Alan dolu. Bu demo doğru / yanlış cevap değerlendirmez.');});answer.addEventListener('input',()=>{if(answer.value.trim()){answer.setAttribute('aria-invalid','false');document.getElementById('answer-error').hidden=true;}});
let timer;document.getElementById('timer-demo').addEventListener('click',()=>{clearInterval(timer);const deadline=Date.now()+15000;const tick=()=>{const n=Math.max(0,Math.ceil((deadline-Date.now())/1000));document.getElementById('time-label').textContent=n+' sn';document.getElementById('round-progress').value=n;document.querySelector('.timer-row').classList.toggle('urgent',n<=5);if(n===0){clearInterval(timer);toast('Süre doldu · görsel demo');}};tick();timer=setInterval(tick,200);});
let raster=false;document.getElementById('asset-toggle').addEventListener('click',()=>{raster=!raster;document.querySelectorAll('.asset-demo').forEach(img=>img.src='../assets/illustrations/'+img.dataset.asset+(raster?'.png':'.svg'));document.getElementById('asset-toggle').textContent=raster?'SVG vektöre dön':'Raster karşılığına geç';});
