# TODO: godot headless server image (export template ile Linux server build)
FROM debian:bookworm-slim
WORKDIR /app
# COPY build/server.x86_64 .
# CMD ["./server.x86_64", "--headless", "--", "--server", "--port", "9080"]
